# Generated by Django 3.1.5 on 2021-01-06 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('audio', models.FileField(upload_to='')),
                ('theme', models.ImageField(upload_to='%d%m%y')),
                ('post_date', models.DateTimeField(default=datetime.datetime(2021, 1, 6, 15, 15, 12, 52931))),
                ('singer', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('link', models.URLField(default='#')),
                ('thumbnail', models.ImageField(upload_to='%d%m%y')),
                ('post_date', models.DateTimeField(default=datetime.datetime(2021, 1, 6, 15, 15, 12, 131134))),
                ('description', models.TextField(max_length=200)),
            ],
        ),
    ]
