# Generated by Django 3.1.5 on 2021-01-06 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 6, 16, 23, 18, 685221)),
        ),
        migrations.AlterField(
            model_name='video',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 6, 16, 23, 18, 763382)),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(upload_to='video thumbnails'),
        ),
    ]
