# Generated by Django 3.1.5 on 2021-01-11 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210107_2004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AlterField(
            model_name='song',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 11, 16, 48, 16, 500402)),
        ),
    ]
