# Generated by Django 3.1.5 on 2021-01-11 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210111_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 11, 16, 49, 15, 534267)),
        ),
    ]
